# Generated by Django 3.1.7 on 2021-04-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPLApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='points',
            field=models.CharField(max_length=3),
        ),
    ]
